name: ${pom.name}
description: ${pom.description}
version: ${pom.version}
website: ${pom.url}
authors: [safoo, Iaccidentally, captbunzo]

main: me.pjt.mailbox.OpenMail
softdepend: [Vault]

commands:
  mail:
    description: mailbox commands
    usage: /mail
  msend:
    description: send a package. The same as /mail send <player_name>.
    usage: /send <player_name>

permissions:
  openmail.*:
    description: Gives access to all mail commands
    children:
      openmail.user.*: true
      openmail.admin.*: true
      openmail.postman.*: true
      openmail.nocooldown: true
      openmail.sendtoself: true

  openmail.user.*:
    description: Gives access to all mail commands
    children:
      openmail.user.create: true
      openmail.user.send: true
      openmail.user.remove: true

  openmail.admin.*:
    description: Gives access to all postman commands
    children:
      openmail.admin.viewlog: true
      openmail.admin.removeany: true

  openmail.postman.*:
    description: Gives access to all postman commands
    children:
      openmail.postman.createother: true
      openmail.postman.removeother: true

  openmail.user.create:
    description: Can create own mailbox.
    default: true

  openmail.user.send:
    description: Can send a package.
    default: true

  openmail.user.remove:
    description: Can remove own mailbox.
    default: true

  openmail.admin.viewlog:
    description: Can view a log.
    default: op

  openmail.admin.removeany:
    description: Can remove any mailbox.
    default: op

  openmail.postman.createother:
    description: Can create a mailbox for someone else.
    default: op

  openmail.postman.removeother:
    description: Can remove mailboxes which he created.
    default: op

  openmail.nocooldown:
    description: Player does not have the send cooldown.
    default: op

  openmail.sendtoself:
    description: Player can send package to himself.
    default: op
